spring.datasource.url=jdbc:mysql://localhost:3306/foodorder_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=8080

app.admin.default.enabled=true
app.admin.default.email=admin@foodorder.com
app.admin.default.password=admin123
app.admin.default.full-name=Admin
app.admin.default.phone=0123456789
app.admin.default.address=Admin Office
